### ISSUE TITLE
issues building solution

### ISSUE THREAD

**Issue by beigewell** [merijnovergaauw/McAfee-SCOM-Management-Pack#1]
this seems to just hang when trying to build the solution. Have tried patching visual studio  and get there same issue. Is this just me
![Screenshot 2022-02-24 131259](https://user-images.githubusercontent.com/15902918/155432479-c5ab75c3-2fa4-4f7a-b517-4e04db403f8b.png)
?

**Comment by merijnovergaauw** [comment]
Hi Richard, I guess there is nothing to create a new built for. Try to do a rebuild.

**Comment by beigewell** [comment]
I havent changed the build at all, that was the issue from a fresh download and just trying to build the solution

**Comment by merijnovergaauw** [comment]
Yes that is what I was trying to say 😉

**Comment by merijnovergaauw** [comment]
Ok just to be sure we are on the same page.

The project that you can download here has already been built. So if you choose to build it again, it won't, as there is nothing added/changed to the project to create a new build for.

However if you do a re-build, a new build will always be triggered.

**Comment by beigewell** [comment]
sorry early morning coffee required, thank you
